export const ReviewCategories: Record<string, string> = {
	bags: "Bags/Panniers",
	components: "Components",
	"camping-gear": "Camping Gear",
	"bike-gear": "Bicycle Gear & Equipment",
	accessories: "Accessories",
	bikes: "Bikes",
	gravel: "Drop-Bar & Gravel Bikes",
	mtb: "Mountain Bikes",
	"fat-bike": "Fat Bikes",
	hardtail: "Hardtail Mountain Bikes",
	"full-suspension": "Full Suspension Mountain Bikes",
	bikepacking: "Bikepacking",
	clothing: "Clothing",
	shoes: "Shoes",
	tools: "Tools",
	tires: "Tires",
	tubes: "Tubes",
	wheels: "Wheels",
	lights: "Lights",
	pedals: "Pedals",
	helmets: "Helmets",
	computers: "Computers",
	locks: "Locks",
	racks: "Racks",
	trailers: "Trailers",
	trainers: "Trainers",
	nutrition: "Nutrition",
	pumps: "Pumps",
	lubes: "Lubes",
	cleaners: "Cleaners",
	"touring": "Bicycle Touring Advice",
	"money": "Budgets & Money"
};
