version: '3'
services:
  cyclershub:
    build: ./
    container_name: cyclershub
    command: pnpm run dev --host
    links:
      - cyclershub-db
    environment:
      PORT: 3000
      DB_CONNECTION: cyclershub-db
      DB_PORT: 5432
      NODE_ENV: "development"
    ports:
      - 3000:3000
    volumes:
      - ./:/cyclershub
    networks:
      - postgres
  cyclershub-db:
    build: ../database
    ports:
      - "5436:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge