version: '3'
services:
  cyclershub:
    entrypoint: ["/bin/sh", "./shutdown-handler.bash"]
    build: ./
    container_name: cyclershub
    command: pnpm run dev --host
    links:
      - cyclershub-db
    environment:
      DB_NAME: main
      DB_PASS: kCKF3ZdUIbCPZF7fwREUJLEevSyyZGWbS68vJSZx5ze4W9PyM9ZXHevtGgScnmRu
      DB_USER: main
      DB_PORT: 5432
      DB_HOST: database
      PORT: 3000
      NODE_ENV: "development"
    ports:
      - 3000:3000
    volumes:
      - ./:/cyclershub
      - ./node_modules/@cyclershub/database:/online-energieausweis/node_modules/@cyclershub/database
      - ./persistent:/persistent
    networks:
      - postgres
  cyclershub-db:
    build: ../database
    env_file:
      - ../database/.env
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge